name: indina
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/indiverse_wordmark.png
    - assets/images/indiverse_icon.png
    - assets/images/indiverse_mark.png
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Variable.ttf
    - family: Tomorrow
      fonts:
        - asset: assets/fonts/Tomorrow-Regular.ttf
    - family: Michroma
      fonts:
        - asset: assets/fonts/Michroma-Regular.ttf
